#!/bin/bash
#
# Generates src/ucanopen_servers/<client>/<client>_od.cpp from the object
# dictionary table of a firmware built on emblib, the rows of
# `emb::can::canopen::od_row<...> rows[] = {...};` in its od.cpp:
#
#   scripts/generate_od.sh adptetk ~/dev/adpt-etk-inverter/src/app/inverter/comm/can/canopen/od.cpp
#
# Each object is one row on one line, its type in the row and its access
# named by the builder:
#
#   {{0x5000, 0x11}, "watch", "elec", "Vdc", "V", float32, od_ro<Vdc>},
#
# Any other line in the table, except blank lines and // comments, is an
# error, so that no object goes missing unnoticed. On an error the output
# file is left as it was.

set -euo pipefail
export LC_ALL=C.UTF-8

die() {
  echo "generate_od.sh: $*" >&2
  exit 1
}

(($# == 2)) || die "usage: generate_od.sh <client> <od.cpp>"
client=$1
source=$2
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
target=$root/src/ucanopen_servers/$client/${client}_od.cpp
[[ -d $(dirname "$target") ]] || die "$client: no such server"
[[ -f $source ]] || die "$source: no such file"

declare -A od_types=(
  [boolean]=OD_BOOL [int8]=OD_INT8 [int16]=OD_INT16 [int32]=OD_INT32
  [uint8]=OD_UINT8 [uint16]=OD_UINT16 [uint32]=OD_UINT32
  [float32]=OD_FLOAT32 [exec]=OD_EXEC [string]=OD_STRING)

table_re='od_row<[^>]*>[[:space:]]+[A-Za-z_][A-Za-z0-9_]*\[\][[:space:]]*=[[:space:]]*\{[[:space:]]*$'
row_re='^\{\{0x([0-9A-Fa-f]{4}), 0x([0-9A-Fa-f]{2})\},[[:space:]]+"([^"\\]*)",[[:space:]]+"([^"\\]*)",[[:space:]]+"([^"\\]*)",[[:space:]]+"([^"\\]*)",[[:space:]]+([a-z0-9]+),[[:space:]]+(.*[^[:space:]])\},[[:space:]]*$'
builder_re='^([A-Za-z_][A-Za-z0-9_]*::)*([A-Za-z_][A-Za-z0-9_]*)(<|$)'

indices=() subindices=() categories=() subcategories=() names=() units=()
accesses=() types=()

state=before
lineno=0
while IFS= read -r line; do
  lineno=$((lineno + 1))
  where=$source:$lineno
  if [[ $state == before ]]; then
    [[ $line =~ $table_re ]] && state=table
    continue
  fi
  if [[ $line =~ ^\}\; ]]; then
    state=after
    break
  fi
  [[ $line =~ ^[[:space:]]*(//.*)?$ ]] && continue

  [[ $line =~ $row_re ]] || die "$where: not a row: $line"
  index=${BASH_REMATCH[1]^^}
  subindex=${BASH_REMATCH[2]^^}
  category=${BASH_REMATCH[3]}
  subcategory=${BASH_REMATCH[4]}
  name=${BASH_REMATCH[5]}
  unit=${BASH_REMATCH[6]}
  type=${od_types[${BASH_REMATCH[7]}]:-}
  [[ -n $type ]] || die "$where: unknown type ${BASH_REMATCH[7]}"
  builder=${BASH_REMATCH[8]}

  [[ $builder =~ $builder_re ]] || die "$where: unknown builder $builder"
  qualifier=${BASH_REMATCH[1]}
  case ${BASH_REMATCH[2]} in
  od_ro) access=OD_ACCESS_RO ;;
  od_const | od_text) access=OD_ACCESS_CONST ;;
  od_wo | od_exec | od_restore_default) access=OD_ACCESS_WO ;;
  od_rw) access=OD_ACCESS_RW ;;
  rw | ro)
    # A settings bridge, as in `param::rw<"drive.pwm_freq">`.
    [[ -n $qualifier ]] || die "$where: unknown builder $builder"
    access=OD_ACCESS_${BASH_REMATCH[2]^^}
    ;;
  *) die "$where: unknown builder $builder" ;;
  esac

  indices+=("$index")
  subindices+=("$subindex")
  categories+=("$category")
  subcategories+=("$subcategory")
  names+=("$name")
  units+=("$unit")
  accesses+=("$access")
  types+=("$type")
done <"$source"
[[ $state == after ]] || die "$source: no complete od_row table"
((${#indices[@]} > 0)) || die "$source: the table has no rows"

if toplevel=$(git -C "$(dirname "$source")" rev-parse --show-toplevel 2>/dev/null); then
  origin="$(realpath --relative-to="$toplevel" "$source")"
  firmware="of the $(basename "$toplevel") firmware. "
else
  origin=$(realpath "$source")
  firmware=""
fi

# Prints the file. Within each run of rows of the same category and
# subcategory the name, unit and access columns are aligned, and a separator
# line follows the run.
generate() {
  local separator count begin end i
  local name_width unit_width access_width name_pad unit_pad access_pad

  printf -v separator '%298s' ''
  separator=//${separator// /#}

  cat <<EOF
#include "${client}_server.hpp"

namespace ${client} {

using namespace ucanopen;

// Generated by scripts/generate_od.sh from ${origin}
// ${firmware}Do not edit.

// clang-format off
extern const ucanopen::ObjectDictionary object_dictionary = {
.config = {
    .watch_category = "watch",
    .config_category = "config"
},
.entries = {
EOF

  count=${#indices[@]}
  begin=0
  while ((begin < count)); do
    end=$((begin + 1))
    while ((end < count)) &&
      [[ ${categories[end]} == "${categories[begin]}" &&
        ${subcategories[end]} == "${subcategories[begin]}" ]]; do
      end=$((end + 1))
    done

    name_width=0 unit_width=0 access_width=0
    for ((i = begin; i < end; ++i)); do
      ((${#names[i]} <= name_width)) || name_width=${#names[i]}
      ((${#units[i]} <= unit_width)) || unit_width=${#units[i]}
      ((${#accesses[i]} <= access_width)) || access_width=${#accesses[i]}
    done

    for ((i = begin; i < end; ++i)); do
      printf -v name_pad '%*s' $((name_width - ${#names[i]} + 1)) ''
      printf -v unit_pad '%*s' $((unit_width - ${#units[i]} + 1)) ''
      printf -v access_pad '%*s' $((access_width - ${#accesses[i]} + 1)) ''
      printf '{{0x%s, 0x%s}, {"%s", "%s", "%s",%s"%s",%s%s,%s%s}},\n' \
        "${indices[i]}" "${subindices[i]}" \
        "${categories[i]}" "${subcategories[i]}" \
        "${names[i]}" "$name_pad" "${units[i]}" "$unit_pad" \
        "${accesses[i]}" "$access_pad" "${types[i]}"
    done
    echo "$separator"
    begin=$end
  done

  cat <<EOF
}
};
// clang-format on

} // namespace ${client}
EOF
}

output=$(mktemp "$target.XXXXXX")
trap 'rm -f -- "$output"' EXIT
generate >"$output"
chmod 644 "$output"
mv -- "$output" "$target"
